language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
install: yarn install
script:
  - npm run lint
  - npm test
  - npm run codecov
  - npm run clean && npm run build
  - npm run build:examples-only && npm run check:examples
after_success:
- bash <(curl -s https://codecov.io/bash)
cache: yarn
cache:
  directories:
  - $HOME/.yarn-cache
notifications:
  email: never
  slack:
    rooms:
      - vega-js:3wQHcSva0iAMeHF2x30X2oGJ
    on_success: never
    on_failure: change
